#include "dynamic_allocator_internal.h"

#define DEFINE_INIT_DYNAMIC_ALLOCATOR(Name, Type) \
    __INTERNAL_INIT_DYNAMIC_ALLOCATOR_IMPL(Name, Type);

#define DEFINE_REALLOC_DYNAMIC_ALLOCATOR(Name, Type) \
    __INTERNAL_REALLOC_DYNAMIC_ALLOCATOR_IMPL(Name, Type);

#define DEFINE_ALLOC_DYNAMIC_ALLOCATOR(Name, Type) \
    __INTERNAL_ALLOC_DYNAMIC_ALLOCATOR_IMPL(Name, Type);

#define DEFINE_PUSH_DYNAMIC_ALLOCATOR(Name, Type) \
    __INTERNAL_PUSH_DYNAMIC_ALLOCATOR_IMPL(Name, Type);

#define DEFINE_GET_MEMORY_DYNAMIC_ALLOCATOR(Name, Type) \
    __INTERNAL_GET_MEMORY_DYNAMIC_ALLOCATOR_IMPL(Name, Type);

#define DEFINE_GET_MEMORY_CONST_DYNAMIC_ALLOCATOR(Name, Type) \
    __INTERNAL_GET_MEMORY_CONST_DYNAMIC_ALLOCATOR_IMPL(Name, Type);

#define DEFINE_RESET_DYNAMIC_ALLOCATOR(Name) \
    __INTERNAL_RESET_DYNAMIC_ALLOCATOR_IMPL(Name);

#define DEFINE_FREE_DYNAMIC_ALLOCATOR(Name) \
    __INTERNAL_FREE_DYNAMIC_ALLOCATOR_IMPL(Name);

#ifdef DYNAMIC_ALLOCATOR_DEF
#   error "Please undef `DYNAMIC_ALLOCATOR_DEF` after you defined it"
#endif

#define DYNAMIC_ALLOCATOR_DEF(Name, Type) \
    __INTERNAL_DEFINE_IS_DYNAMIC_ALLOCATOR_VALID(Name); \
    DEFINE_INIT_DYNAMIC_ALLOCATOR(Name, Type); \
    DEFINE_REALLOC_DYNAMIC_ALLOCATOR(Name, Type); \
    DEFINE_ALLOC_DYNAMIC_ALLOCATOR(Name, Type); \
    DEFINE_PUSH_DYNAMIC_ALLOCATOR(Name, Type); \
    DEFINE_GET_MEMORY_DYNAMIC_ALLOCATOR(Name, Type); \
    DEFINE_GET_MEMORY_CONST_DYNAMIC_ALLOCATOR(Name, Type); \
    DEFINE_RESET_DYNAMIC_ALLOCATOR(Name); \
    DEFINE_FREE_DYNAMIC_ALLOCATOR(Name);
#include "dynamic_allocator.x"
#undef DYNAMIC_ALLOCATOR_DEF

#undef DEFINE_INIT_DYNAMIC_ALLOCATOR
#undef __INTERNAL_DEFINE_IS_DYNAMIC_ALLOCATOR_VALID
#undef __INTERNAL_IS_DYNAMIC_ALLOCATOR_VALID
#undef DEFINE_REALLOC_DYNAMIC_ALLOCATOR
#undef DEFINE_ALLOC_DYNAMIC_ALLOCATOR
#undef DEFINE_PUSH_DYNAMIC_ALLOCATOR
#undef DEFINE_GET_MEMORY_DYNAMIC_ALLOCATOR
#undef DEFINE_GET_MEMORY_CONST_DYNAMIC_ALLOCATOR
#undef DEFINE_RESET_DYNAMIC_ALLOCATOR
#undef DEFINE_FREE_DYNAMIC_ALLOCATOR
#undef DEFINE_DYNAMIC_ALLOCATOR

// Undef internals
#undef __INTERNAL_DEFINE_IS_DYNAMIC_ALLOCATOR_VALID
#undef __INTERNAL_IS_DYNAMIC_ALLOCATOR_VALID
#undef __INTERNAL_INIT_DYNAMIC_ALLOCATOR_IMPL
#undef __INTERNAL_DEFINE_IS_DYNAMIC_ALLOCATOR_VALID
#undef __INTERNAL_REALLOC_DYNAMIC_ALLOCATOR_IMPL
#undef __INTERNAL_ALLOC_DYNAMIC_ALLOCATOR_IMPL
#undef __INTERNAL_PUSH_DYNAMIC_ALLOCATOR_IMPL
#undef __INTERNAL_GET_MEMORY_DYNAMIC_ALLOCATOR_IMPL
#undef __INTERNAL_GET_MEMORY_CONST_DYNAMIC_ALLOCATOR_IMPL
#undef __INTERNAL_RESET_DYNAMIC_ALLOCATOR_IMPL
#undef __INTERNAL_FREE_DYNAMIC_ALLOCATOR_IMPL